#!/bin/bash

# CERN-related aliases and functions

# variables to define in env:
# CERN_MACHINES: array of machines to make background connections to
# CERN_USER: cern username for tunnel
# CERN_NAME: user name for git config
# CERN_EMAIL: cern email for git config
# CERN_SIGNINGKEY: gpg key for signing commits

function gitcern() {
  git config --local user.name "$CERN_NAME"
  git config --local user.email "$CERN_EMAIL"
  git config --local user.signingkey "$CERN_SIGNINGKEY"
}

# dynamic tunnel
function cerntunnel() {
  case $@ in
    connect)
      ssh -4 -D localhost:1337 -S /tmp/.ssh-lxtunnel -M -fN "$CERN_USER"@lxtunnel.cern.ch -E /tmp/.ssh-lxtunnel-log
      shift
    ;;
    disconnect)
      ssh -S /tmp/.ssh-lxtunnel -O exit "$CERN_USER"@lxtunnel.cern.ch
      shift
    ;;
    *)
      # unknown option
      echo "Usage: tunnel.sh [connect|disconnect]"
   ;;
  esac
}

# curl using socket
alias curlcern='curl -x socks5h://localhost:1337'

function work() {
  (
    set -e
    echo 'Connecting tunnel...'
    cerntunnel connect
    echo 'Obtaining Kerberos ticket...'
    kinit "$CERN_USER"
    echo 'Setting up background SSH connections...'
    for machine in "${CERN_MACHINES[@]}"
    do
      sb "$machine"
    done
  )
}

function workdone() {
  echo 'Disconnecting tunnel...'
  cerntunnel disconnect
  echo 'Clearing Kerberos tickets...'
  kdestroy
  echo 'Killing background SSH connections...'
  kill_sbs
  echo 'All done, have fun!'
}
