#!/bin/bash

# clean all images and containers
function dockerpurge() {
    echo "This will remove all Docker images and containers. Are you sure?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) sudo docker rm "$(sudo docker ps -a -q)"; sudo docker rmi "$(sudo docker images -q)"; break;;
            No ) break;;
        esac
    done

    # =''
}

# shell in runnning container
function dci() {
    docker exec -it "$@" /bin/bash
}

function dcish() {
    docker exec -it "$@" /bin/sh
}

# images
alias dils='docker image ls'
alias dilsa='docker image ls -a'
dirm() { docker image rm "$@" ; }

# containers
alias dcls='docker container ls'
alias dclsa='docker container ls -a'
dcrm() { docker container rm "$@" ; }

# volumes
alias dvls='docker volume ls'
dvrm() { docker volume rm "$@" ; }

# docker-compose
alias dcup='docker-compose up'
alias dcupd='docker-compose up -d'
alias dcupb='docker-compose up --build'
alias dcupdb='docker-compose up -d --build'
alias dcdown='docker-compose down'
