#!/bin/bash

# clean all images and containers
function ,docker_purge() {
    echo "This will remove all Docker images and containers. Are you sure?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) sudo docker rm "$(sudo docker ps -a -q)"; sudo docker rmi "$(sudo docker images -q)"; break;;
            No ) break;;
        esac
    done

    # =''
}

# shell in running container
function ,docker_it() {
    docker exec -it "$@" /bin/bash || docker exec -it "$@" /bin/sh
}

# images
alias dils='docker image ls'
alias dilsa='docker image ls -a'
dirm() { docker image rm "$@" ; }

# containers
alias dcls='docker container ls'
alias dclsa='docker container ls -a'
dcrm() { docker container rm "$@" ; }

# volumes
alias dvls='docker volume ls'
dvrm() { docker volume rm "$@" ; }

# docker-compose
alias dcup='docker compose up'
alias dcupd='docker compose up -d'
alias dcupb='docker compose up --build'
alias dcupdb='docker compose up -d --build'
alias dcdown='docker compose down'

alias dps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Command}}\t{{.RunningFor}}\t{{.Status}}\t{{.Size}}\t{{.Names}}"'
