#!/bin/bash

# oneliner with relative/absolute date
alias gl1="git log --color=always --graph --pretty=tformat:'%C(bold yellow)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an - %aE>%Creset' --abbrev-commit --date=relative"
alias gl1s="git log --color=always --graph --pretty=tformat:'%C(bold yellow)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an - %aE>%Creset' --abbrev-commit --date=relative --show-signature"
alias gl1np="git --no-pager log --color=always --graph --pretty=tformat:'%C(bold yellow)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an - %aE>%Creset' --abbrev-commit --date=relative"
alias gl1a="git log --color=always --graph --pretty=tformat:'%C(bold yellow)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an - %aE>%Creset' --abbrev-commit --date=absolute"

alias gits="git status"
alias gitd="git diff"
alias gitp="git push"
alias gita="git add -A && git commit --amend --no-edit && git push -f --force-with-lease"
alias gito="git open"

alias gitri="git rebase -i"
alias gitrc="git rebase --continue"
alias gitcpc="git cherry-pick --continue"

git config --global commit.gpgsign true

function ,git_work() {
  git config --local user.name "$GIT_NAME"
  git config --local user.email "$GIT_WORK_EMAIL"
  git config --local user.signingkey "$GIT_WORK_SIGNINGKEY"
}

function ,git_pers() {
  git config --local user.name "$GIT_NAME"
  git config --local user.email "$GIT_PERSONAL_EMAIL"
  git config --local user.signingkey "$GIT_PERSONAL_SIGNINGKEY"
}
