#!/bin/bash

function activate() {
  if [[ -d ./venv ]]
  then
    source ./venv/bin/activate
  elif [[ -d ./env ]]
  then
    source ./env/bin/activate
  elif [[ -d ./.venv ]]
  then
    source ./.venv/bin/activate
  else
    echo "No python virtualenv found in ./venv, ./env or ./.venv"
  fi
}

# rye
[ -f "$HOME/.rye/env" ] && source "$HOME/.rye/env"
