#!/bin/bash

alias pipins="pip install --editable ."

function activate() {
  if [[ -d ./venv ]]
  then
    source ./venv/bin/activate
  elif [[ -d ./env ]]
  then
    source ./env/bin/activate
  else
    echo "No python virtualenv found in ./venv or ./env"
  fi
}

# rye
[ -f "$HOME/.rye/env" ] && source "$HOME/.rye/env"
